### ISSUE TITLE
Test1 sửa chân trang Sao vàng mekong

### ISSUE THREAD

**Issue by PhanDung123** [optimusteamvn/saovangmekong2019#1]
Sửa chân trang

**Comment by quyenquyen** [comment]
Đã sửa
![hinh](https://user-images.githubusercontent.com/47210530/52098491-c432d800-2601-11e9-8bcc-7a93d310956f.PNG)

**Comment by PhanDung123** [comment]
![hinh1](https://user-images.githubusercontent.com/47210529/52098470-af564480-2601-11e9-9f0f-9e12480cb2dc.jpg)
Hình hiện tại là  mẫu
![hinh 2](https://user-images.githubusercontent.com/47210529/52098497-ce54d680-2601-11e9-8db5-96fde8125df0.jpg)

**Comment by quyenquyen** [comment]
Đã nhận đc assigned
